using HarmonyLib;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Rooms;

public static class RelicExclusionManager
{
    private static readonly HashSet<string> ExcludedRelics = new HashSet<string>
    {
        "ALCHEMICAL_COFFER",
        "ARCANE_SCROLL",
        "ARCHAIC_TOOTH",
        "ASTROLABE",
        "BEAUTIFUL_BRACELET",
        "BONE_TEA",
        "BYRDPIPE",
        "CALLING_BELL",
        "CLAWS",
        "DOLLYS_MIRROR",
        "DUSTY_TOME",
        "ELECTRIC_SHRYMP",
        "EMPTY_CAGE",
        "FRAGRANT_MUSHROOM",
        "FUR_COAT",
        "GIRYA",
        "GLASS_EYE",
        "GLITTER",
        "GNARLED_HAMMER",
        "GOLDEN_COMPASS",
        "GOLDEN_PEARL",
        "JEWELRY_BOX",
        "JUZU_BRACELET",
        "KIFUDA",
        "LARGE_CAPSULE",
        "LAVA_ROCK",
        "LEAD_PAPERWEIGHT",
        "LEAFY_POULTICE",
        "LIZARD_TAIL",
        "LOOMING_FRUIT",
        "LOST_COFFER",
        "MANGO",
        "MASSIVE_SCROLL",
        "MEAT_CLEAVER",
        "MINIATURE_TENT",
        "NEOWS_TORMENT",
        "NEW_LEAF",
        "NUTRITIOUS_OYSTER",
        "NUTRITIOUS_SOUP",
        "OLD_COIN",
        "ORRERY",
        "PAELS_CLAW",
        "PAELS_HORN",
        "PAELS_TOOTH",
        "PEAR",
        "POMANDER",
        "POTION_BELT",
        "PRECARIOUS_SHEARS",
        "PRECISE_SCISSORS",
        "PRESERVED_FOG",
        "PUNCH_DAGGER",
        "ROYAL_STAMP",
        "SAND_CASTLE",
        "SCROLL_BOXES",
        "SEA_GLASS",
        "SIGNET_RING",
        "SMALL_CAPSULE",
        "SWORD_OF_STONE",
        "TANXS_WHISTLE",
        "TOUCH_OF_OROBAS",
        "TOY_BOX",
        "WAR_PAINT",
        "WHETSTONE",
        "WONGO_CUSTOMER_APPRECIATION_BADGE",
        "WONGOS_MYSTERY_TICKET",
        "FAKE_MANGO",
        "SILVER_CRUCIBLE",
        "CURSED_PEARL",
        "DINGY_RUG",
        "GHOST_SEED",
        "ICE_CREAM",
        "LORDS_PARASOL",
        "PAELS_LEGION",
        "RED_SKULL",
        "STRAWBERRY",
        "STORYBOOK",
        "MEMBERSHIP_CARD"
    };

    public static bool IsRelicExcluded(string relicId)
    {
        return ExcludedRelics.Contains(relicId);
    }
}
